### ISSUE TITLE
site crashes on reload

### ISSUE THREAD

**Issue by phreid** [nyananu/somethingBorrowed#124]
if you reload the deployed site, it crashes.

from the heroku logs; 

```
2022-08-04T05:31:21.408689+00:00 app[web.1]: URIError: Failed to decode param '/%PUBLIC_URL%/favicon.ico'
2022-08-04T05:31:21.408701+00:00 app[web.1]:     at decodeURIComponent (<anonymous>)
2022-08-04T05:31:21.408702+00:00 app[web.1]:     at decode_param (/app/node_modules/express/lib/router/layer.js:172:12)
2022-08-04T05:31:21.408702+00:00 app[web.1]:     at Layer.match (/app/node_modules/express/lib/router/layer.js:123:27)
2022-08-04T05:31:21.408702+00:00 app[web.1]:     at matchLayer (/app/node_modules/express/lib/router/index.js:585:18)
2022-08-04T05:31:21.408703+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:226:15)
2022-08-04T05:31:21.408703+00:00 app[web.1]:     at SendStream.error (/app/node_modules/serve-static/index.js:121:7)
2022-08-04T05:31:21.408703+00:00 app[web.1]:     at SendStream.emit (events.js:400:28)
2022-08-04T05:31:21.408704+00:00 app[web.1]:     at SendStream.error (/app/node_modules/send/index.js:270:17)
2022-08-04T05:31:21.408704+00:00 app[web.1]:     at SendStream.pipe (/app/node_modules/send/index.js:516:10)
2022-08-04T05:31:21.408705+00:00 app[web.1]:     at serveStatic (/app/node_modules/serve-static/index.js:125:12)
2022-08-04T05:31:21.406365+00:00 heroku[router]: at=info method=GET path="/%PUBLIC_URL%/favicon.ico" host=something-borrowed-cpsc455.herokuapp.com request_id=2f4ddc88-bec7-4fd2-8f7f-21068b5b1470 fwd="174.6.13.221" dyno=web.1 connect=0ms service=2ms status=400 bytes=438 protocol=https
```

**Comment by imogenem** [comment]
I got this on Marketplace before re-seeding the db
```
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading '_id')
    at MarketplacePage.jsx:19:47
    at Array.map (<anonymous>)
    at xw (MarketplacePage.jsx:19:31)
    at Oi (react-dom.production.min.js:167:137)
    at Cu (react-dom.production.min.js:197:258)
    at Sl (react-dom.production.min.js:292:88)
    at bs (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at ms (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
```

**Comment by phreid** [comment]
Does it crash if you reload the site?

**Comment by imogenem** [comment]
Yeah, same error

**Comment by nyananu** [comment]
> 
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.
      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
   
This is what we have currently in the frontend -> public-> index.html 
 Can we try replacing `%PUBLIC_URL%/favicon.ico` with `/public/favicon.ico` as this[ post](https://stackoverflow.com/questions/50824024/urierror-failed-to-decode-param-public-url-favicon-ico) suggests?

On the network tab, it is showing as a 400 bad request, I believe the server is taking a long time to respond. I tried it in incognito mode as well (hoping there won't be cache issues), but it crashes on incognito as well. Googling around said that every time the site is reloaded because we are giving it a URL, it will fetch the favicon. It might work if we just pointed it to the favicon using the directory method (like in the StackOverflow post). Can someone check this, please? (asking cux I'm nervous deploying stuff into main)
 
 PS: in my **brand branch** (which is still a WIP), I am not using the favicon given in the public folder. I added a new logo to show up in the browser tab when we open our site. Locally everything works, and it doesn't crash on reloading.

**Comment by phreid** [comment]
@nyananu tried the fix from that post, it fixed the error from the log, but the site still crashes on reload. this time with no error message or other indication of what went wrong that i can see

**Comment by phreid** [comment]
fixed i think. this was the issue: https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing. 

can someone test it out?
